const TICKETS = "TICKETS";
const FILTER_MORE_TICKETS = "FILTER-MORE_TICKETS";
const SET_CHECKED_lIST = "SET-CHECKED-lIST";
const SET_CHECK_ALL = "SET_CHECK_ALL";
const SET_RADIO = "SET-RADIO";
const BUTTON_FAST = "BUTTON-FAST";
const BUTTON_SALES = "BUTTON_SALES";
const BUTTON_OPTIMAL = "BUTTON-OPTIMAL";
export {
  TICKETS,
  FILTER_MORE_TICKETS,
  SET_CHECK_ALL,
  SET_CHECKED_lIST,
  SET_RADIO,
  BUTTON_SALES,
  BUTTON_FAST,
  BUTTON_OPTIMAL,
};
